### ISSUE TITLE
Crashed from MineTogether/MineTogetherServer

### ISSUE THREAD

**Issue by BeholdBlaze** [CreeperHost/CreeperHostGui#61]
My ModPack Version is 1.6.0 of StoneBlock 2, I've encountered this issue out of random by simply trying to join my single player world 2 days ago. it will load fine until i'm about to join the world then it crashes, Vanilla Fix is installed so I can still continue, but it tells me that the potential cause was MineTogether and MineTogetherServer.

The Crash log is here - https://paste.dimdev.org/dijucuvuye.mccrash
It is repeatable and I have no issue with any other modpack.

**Comment by gigabit101** [comment]
This has already been fixed in dev, We hope to have a new build out soon.

**Comment by AdinDRAK** [comment]
I didnt get it so is it fixed?

**Comment by gigabit101** [comment]
fixed in dev, few more things to fix/add before a new release

**Comment by AdinDRAK** [comment]
Im not that good at english so what should i do? My game is updated

**Comment by AdinDRAK** [comment]
This is my crash log: https://paste.dimdev.org/apopiwigat.mccrash

**Comment by gigabit101** [comment]
You will need to delete the Minetogether config from the configs folder.

**Comment by AdinDRAK** [comment]
It doesnt work

**Comment by Liquidmasl** [comment]
I have the same problem, and it appeared all of a sudden.

Last few days everything worked flawlessly, booked hundreds of hours into the server. suddenly today i cant start the server anymore. same problem as Adin.

My server is hosted locally for me and friends, running FTB revelation.

I really want this server to be running, and also i dont really need this mod at all. but when i delete it the server doest start correctly.

Any advice on how to get the server running without your fix? (or until your fix is published?)

**Comment by Cloudhunter** [comment]
ALL HAIL @GIGABIT101 THE MIGHTY FIXER

**Comment by gigabit101** [comment]
This was fixed in the last release

**Comment by TheCriticalHit-No1** [comment]
I installed StoneBlock 2 not to long ago and it ran fine, then this morning, the modpack starts fine and i load my singleplayer world, however when I'm about to join and it crashes due to MineTogether, and MineTogether Server, I came to this and did everything mentioned and its still crashing, its also the newest version...

**Comment by AL42Gaming** [comment]
same
